root: true
parser: babel-eslint
parserOptions:
  sourceType: module
extends:
- airbnb-base
plugins:
- html
settings:
  import/resolver: webpack
  html/html-extensions:
  - .html
  - .vue
rules:
  prefer-destructuring: off
  import/prefer-default-export: off
  no-underscore-dangle: off
  indent:
  - error
  - tab
  no-tabs: off
  arrow-parens:
  - error
  - as-needed
  no-plusplus: off
  space-unary-ops:
  - error
  - words: true
    nonwords: false
    overrides:
      "!": true
      "!!": true
